{...}: {
	imports = [
		./gnome.nix
        ./zoxide.nix
        ./nvim
		./vim

        # settings for gnome
        # generated by dconf2nix tool
        #                 dconf dump / > dconf.settings
        #                 dconf2nix -i dconf.settings -o dconf.nix
        ./dconf.nix
	];
}
