#!/usr/bin/bash
#  
#	I have many aliases to directories i constantly Visit.
# 	
#	For Example: `cdc` is an alias to my c workingspace 
#	running `alias cdc` gives `/home/aldrich/Documents/workspace/cspace/github.com`
#
# 	Those aliases are good for easily changing directories
#	but sometimes i want to (do stuff with them) other than cding
#	
# 	For Example:
#		If I have to copy a file a.txt to the `c dir` I have to type the whole directory manually like
#			```cd a.txt /home/aldrich/Documents/workspace/cspace/github.com/jossephus```
#
#	instead of writing the whole directory by hand I would rather 
#	extract it from the aliases i use. like
#
#			````cd a.txt `imalias cdc`/jossephus````
#
#
temp=$(mktemp)

cat > $temp << ALIASFILE
	import "os" for Process

	if (Process.arguments.count == 0) return

	var path = Process.arguments[2]

	var expanded = path.replace("WORKSPACE", "/home/aldrich/Documents/workspace")
	expanded = expanded.replace("$", "")[0...expanded.count - 2]
	System.print(expanded)
ALIASFILE

aliased=`alias $@`
wren $temp $aliased

rm -r $temp
